---
name: NginxReverse
version: 1.2
slug: nginx_reverse
description: Nginx Server/Reverse proxy on HomeAssistant
url: https://github.com/sdavides/NginxReverse-Homeassistant
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:nuxt
init: false
homeassistant: 2023.3.0
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 
ports_description:
  80/tcp: Nginx external port additional (direct port)
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  upstream_server: "192.168.1.1"
  upstream_port: "80"
  upstream_http: "http"
  basic_authentication_username: ""
  basic_authentication_password: ""
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  leave_front_door_open: false
  fix_resource_proxy_redirect: false
schema:
  upstream_server: str
  upstream_port: str
  upstream_http: str
  basic_authentication_username: str?
  basic_authentication_password: str?
  upstream_http: list(http|https)?
  ssl: bool?
  certfile: str?
  keyfile: str?
  leave_front_door_open: bool?
  apache: bool?
  fix_resource_proxy_redirect: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
