---
name: NginxReverse
version: dev
slug: nginx_reverse
description: Nginx Server/Reverse proxy on HA
url: https://github.com/sdavides/NginxReverse-Homeassistant
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:nuxt
init: false
homeassistant: 2023.3.0
arch:
  - aarch64
  - amd64
  - armv7
ports:
  80/tcp: 1890
ports_description:
  80/tcp: Nginx local port
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  upstream_server: 
  upstream_port: "80"
  upstream_http: "http"
  upstream_documentroot: ""
  basic_authentication:
    info: add login if backend require basic authentication
    username: ""
    password: ""
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  upstream_server: str
  upstream_port: str
  upstream_http: str
  upstream_documentroot: str
  basic_authentication:
    username: str
    password: str
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?

  log_level: list(trace|debug|info|notice|warning|error|fatal)?